language: python
python: 
  - "3.6"

services:
  - docker


before_script: pip install docker-compose

script: 
  - |
    docker-compose run
    -e AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
    -e AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
    -e SECRET_KEY=$SECRET_KEY
    -e AWS_STORAGE_BUCKET_NAME=$AWS_STORAGE_BUCKET_NAME
    -e AWS_S3_REGION_NAME=$AWS_S3_REGION_NAME
    django sh -c "python manage.py test"